# Service name: rapid_pbd/create_program
# The service takes an empty request, create a program, and
# Reply the program id to the service caller

# Request:
string name # Refers to program name
---
# Response:
string db_id # Refers to program id